version: '3.9'

services:
    base-ms-db:
        image: mongo:7.0
        container_name: base-ms-db
        ports:
            - '27017:27017'
        environment:
            TZ: America/Sao_Paulo
            MONGO_INITDB_DATABASE: base
        volumes:
            - mongo-data:/data/db
        command: --logpath=/dev/null
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/base --quiet
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - base-net
        restart: unless-stopped

    base-ms-app:
        container_name: base-ms-app
        build:
            context: .
            dockerfile: Dockerfile
        command: ./start.sh
        env_file:
            - .env
        ports:
            - '3002:3000'
            - '9229:9229'
        volumes:
            - .:/usr/app/current
        depends_on:
            base-ms-db:
                condition: service_healthy
        networks:
            - base-net
        restart: unless-stopped

volumes:
    mongo-data:

networks:
    base-net:
